const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx={console,Date,Math,document:{getElementById:()=>null}};
ctx.window={G:{S:{day:6,heroes:[{id:'h1',name:'Роман',role:'Штурмовик',hp:100},{id:'h2',name:'Лена',role:'Медик',hp:35},{id:'h3',name:'Ирина',role:'Инженер',hp:100}],squadAI:{squads:{alpha:{id:'alpha',heroes:['h1','h2','h3'],formation:'shield',history:[]}},active:{alpha:true},history:[],enabled:true}},squadAI:null,baseDefenseState:()=>({active:{status:'active',zombies:[{id:'z1',type:'runner',hp:60,maxHp:100,x:.2,y:.1},{id:'z2',type:'tank',hp:180,maxHp:200,x:.8,y:.8}]}})}};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync('js/base-defense-stage3v.js','utf8'),ctx);
vm.runInContext(fs.readFileSync('js/base-defense-stage3w.js','utf8'),ctx);
const G=ctx.window.G;
assert(G.advancedSquadTactics.focus('alpha','z1'));
assert(G.advancedSquadTactics.state().orders.alpha.order==='focus');
assert(G.advancedSquadTactics.plan('alpha').some(x=>x.action==='attack'));
assert(G.advancedSquadTactics.flank('alpha','z2'));
assert(G.advancedSquadTactics.plan('alpha').some(x=>x.action==='flank'));
assert(G.advancedSquadTactics.cover('alpha','h2'));
assert(G.advancedSquadTactics.plan('alpha').some(x=>x.action==='protect'));
assert(G.advancedSquadTactics.rescue('alpha','h2'));
assert(G.advancedSquadTactics.plan('alpha').some(x=>x.action==='rescue'));
assert(G.advancedSquadTactics.switchFormation('alpha','wedge'));
assert(G.squadAI.state().squads.alpha.formation==='wedge');
assert(G.advancedSquadTactics.retreat('alpha'));
assert(G.advancedSquadTactics.plan('alpha').every(x=>x.action==='retreat'));
assert(G.advancedSquadTactics.enable(false)===false&&G.advancedSquadTactics.tick().length===0);
console.log('Stage 3W Advanced Squad Tactics: 10/10 passed');
