const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const base=fs.readFileSync(path.join(__dirname,'../js/living-commune.js'),'utf8');
const drama=fs.readFileSync(path.join(__dirname,'../js/living-drama.js'),'utf8');
const elements={};
const ctx={console,Date,Math,setInterval:()=>{},setTimeout:(fn)=>fn(),window:{},document:{getElementById:id=>elements[id]||null,createElement:()=>({style:{},classList:{add(){},remove(){}},appendChild(){},setAttribute(){}}),body:{appendChild(){}}}};ctx.window=ctx;
ctx.G={S:{heroes:[{id:'a',n:'Анна',loyalty:90},{id:'b',n:'Илья',loyalty:80},{id:'c',n:'Михаил',loyalty:70}],res:{food:100}},SUBS:{heroes:['specialists','bonds']},toast(){},save(){},updTop(){},rPanel(){}};
vm.createContext(ctx);vm.runInContext(base,ctx);vm.runInContext(drama,ctx);
ctx.G.livingTalk('a','b');ctx.G.livingTalk('a','b');ctx.G.livingTalk('a','b');ctx.G.livingTalk('a','b');ctx.G.livingTalk('a','b');
assert(ctx.G.setLivingRomance('a','b'),'romance should start');
assert(ctx.TLP_LivingDrama.state().pairs['a::b'].type==='romance');
ctx.G.loseLivingHero('b','Погиб в обороне');
assert(ctx.G.S.heroes[1].living.status==='dead');
assert((ctx.G.S.heroes[0].living.grief||0)>0,'close survivor should grieve');
assert(ctx.TLP_LivingDrama.state().dead.length===1);
assert(ctx.G.startLivingStory('mourning','a'));
const s=ctx.TLP_LivingDrama.state().stories.find(x=>x.type==='mourning');
assert(s&&s.active);
ctx.G.resolveLivingStory(s.id,'talk');
assert(s.step===1);
console.log('PASS: Living Drama Stage 1C');
